
apiVersion: v1
kind: Service
metadata:
  name: {{ include "quickstart-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "quickstart-chart.name" . }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
